//! Run the shipped components in a real WebAssembly runtime.
//!
//! Everything else in this repository tests the Rust source. `cargo test`
//! links the plugin crates as `rlib`s and calls their pure logic directly; the
//! conformance arena does the same. The `.wasm` an operator actually installs
//! gets built and linted, and until now was never executed by anything except
//! ZeroClaw itself.
//!
//! That is a real gap for a security tool. The source is what we audit; the
//! component is what refuses the payment. This binary closes it by loading the
//! staged artifact into wasmtime, granting it exactly the host imports the
//! ZeroClaw runtime grants, calling `execute` across the component boundary,
//! and asserting the verdict that comes back.
//!
//! It answers a question the source-level tests structurally cannot: does the
//! thing we ship still refuse what it is supposed to refuse, after
//! wit-bindgen, after the component-model lowering, after optimisation?
//!
//! ```sh
//! cargo run --release --manifest-path component-test/Cargo.toml
//! ```

use anyhow::{bail, Result};
use std::path::{Path, PathBuf};
use wasmtime::component::{Component, Linker, ResourceTable};
use wasmtime::{Config, Engine, Store};
use wasmtime_wasi::{WasiCtx, WasiCtxBuilder, WasiCtxView, WasiView};
use wasmtime_wasi_http::p2::{WasiHttpCtxView, WasiHttpView};
use wasmtime_wasi_http::WasiHttpCtx;

mod cases;

wasmtime::component::bindgen!({
    // Generated by build.rs from ../wit/v0 with the @unstable gates stripped;
    // wasmtime's host bindgen has no features option. See build.rs.
    path: "wit-generated",
    world: "tool-plugin",
});

const GREEN: &str = "\x1b[32m";
const RED: &str = "\x1b[31m";
const DIM: &str = "\x1b[2m";
const BOLD: &str = "\x1b[1m";
const RESET: &str = "\x1b[0m";

/// Host state handed to the component: WASI plus the ZeroClaw logging import.
struct Host {
    table: ResourceTable,
    wasi: WasiCtx,
    http: WasiHttpCtx,
    /// Log records the component emitted, kept so a test can assert a plugin
    /// reported a failure rather than silently swallowing one.
    logs: Vec<String>,
}

impl WasiView for Host {
    fn ctx(&mut self) -> WasiCtxView<'_> {
        WasiCtxView {
            ctx: &mut self.wasi,
            table: &mut self.table,
        }
    }
}

impl WasiHttpView for Host {
    fn http(&mut self) -> WasiHttpCtxView<'_> {
        WasiHttpCtxView {
            ctx: &mut self.http,
            table: &mut self.table,
            hooks: Default::default(),
        }
    }
}

// The host side of `zeroclaw:plugin/logging`. The real runtime forwards these
// into its structured log; here they are captured so assertions can see them.
impl zeroclaw::plugin::logging::Host for Host {
    fn log_record(
        &mut self,
        level: zeroclaw::plugin::logging::LogLevel,
        event: zeroclaw::plugin::logging::PluginEvent,
    ) {
        self.logs
            .push(format!("{level:?} {} — {}", event.function_name, event.message));
    }
}

impl zeroclaw::plugin::types::Host for Host {}

/// wasmtime 47 projects host state through a marker type rather than the
/// state type itself. This says: the imports are implemented on `Host`.
struct HostData;

impl wasmtime::component::HasData for HostData {
    type Data<'a> = &'a mut Host;
}

/// One component, instantiated and ready to be called.
struct Plugin {
    store: Store<Host>,
    bindings: ToolPlugin,
}

impl Plugin {
    fn load(engine: &Engine, wasm: &Path) -> Result<Self> {
        let component = Component::from_file(engine, wasm)
            .map_err(|e| anyhow::anyhow!("loading component {}: {e}", wasm.display()))?;

        let mut linker = Linker::new(engine);
        // Exactly what ZeroClaw grants a tool plugin: WASI p2 plus outbound
        // HTTP. No filesystem is preopened, matching the host, so a component
        // that tried to touch disk would fail here as it would in production.
        wasmtime_wasi::p2::add_to_linker_sync(&mut linker)?;
        wasmtime_wasi_http::p2::add_only_http_to_linker_sync(&mut linker)?;
        ToolPlugin::add_to_linker::<Host, HostData>(&mut linker, |state: &mut Host| state)?;

        let mut store = Store::new(
            engine,
            Host {
                table: ResourceTable::new(),
                wasi: WasiCtxBuilder::new().build(),
                http: WasiHttpCtx::new(),
                logs: Vec::new(),
            },
        );
        let bindings = ToolPlugin::instantiate(&mut store, &component, &linker)
            .map_err(|e| anyhow::anyhow!("instantiating the component: {e}"))?;
        Ok(Self { store, bindings })
    }

    fn name(&mut self) -> Result<String> {
        self.bindings
            .zeroclaw_plugin_tool()
            .call_name(&mut self.store)
            .map_err(|e| anyhow::anyhow!("calling name(): {e}"))
    }

    fn execute(&mut self, args: &str) -> Result<Result<ToolOutcome, String>> {
        let raw = self
            .bindings
            .zeroclaw_plugin_tool()
            .call_execute(&mut self.store, &args.to_string())
            .map_err(|e| anyhow::anyhow!("calling execute(): {e}"))?;
        Ok(raw.map(|result| ToolOutcome {
            success: result.success,
            output: result.output,
            error: result.error,
        }))
    }
}

pub struct ToolOutcome {
    pub success: bool,
    pub output: String,
    pub error: Option<String>,
}

impl ToolOutcome {
    /// The verdict the component reported, if its output carries one.
    pub fn verdict(&self) -> Option<String> {
        serde_json::from_str::<serde_json::Value>(&self.output)
            .ok()?
            .get("verdict")?
            .as_str()
            .map(str::to_string)
    }

    /// Everything the component said, for matching reason codes against.
    pub fn text(&self) -> String {
        format!("{} {}", self.output, self.error.clone().unwrap_or_default())
    }
}

fn staged_dir() -> PathBuf {
    std::env::args()
        .nth(1)
        .map(PathBuf::from)
        .unwrap_or_else(|| {
            Path::new(env!("CARGO_MANIFEST_DIR"))
                .parent()
                .expect("component-test lives in the repository")
                .join("dist")
                .join("local")
        })
}

fn main() -> Result<()> {
    let staged = staged_dir();
    if !staged.is_dir() {
        bail!(
            "{} not found — run `just stage-local` first",
            staged.display()
        );
    }

    let mut config = Config::new();
    config.wasm_component_model(true);
    let engine = Engine::new(&config)?;

    println!(
        "\n{BOLD}Safe Hands — executing the shipped components{RESET}\n{DIM}staged: {}{RESET}\n",
        staged.display()
    );

    let mut passed = 0usize;
    let mut failed = 0usize;

    for case in cases::all() {
        let wasm = staged.join(case.plugin).join(case.wasm);
        if !wasm.is_file() {
            println!("  {RED}MISSING{RESET} {} ({})", case.name, wasm.display());
            failed += 1;
            continue;
        }

        let mut plugin = Plugin::load(&engine, &wasm)?;
        let tool_name = plugin.name()?;
        if tool_name != case.plugin {
            println!(
                "  {RED}FAIL{RESET}  {} — component reports tool name {tool_name:?}, expected {:?}",
                case.name, case.plugin
            );
            failed += 1;
            continue;
        }

        let outcome = plugin.execute(&case.args)?;
        match (case.check)(&outcome) {
            Ok(detail) => {
                passed += 1;
                println!("  {GREEN}PASS{RESET}  {}\n        {DIM}{detail}{RESET}", case.name);
            }
            Err(reason) => {
                failed += 1;
                println!("  {RED}FAIL{RESET}  {}\n        {DIM}{reason}{RESET}", case.name);
            }
        }
    }

    println!("\n{passed} passed, {failed} failed");
    if failed > 0 {
        bail!("the shipped components did not behave as the source-level tests claim");
    }
    println!(
        "{GREEN}Every verdict above came out of a real WebAssembly instance, \
         across the component boundary.{RESET}\n"
    );
    Ok(())
}
