#!/usr/bin/env python3
"""Prove the operator config surface is closed, described and no wider than the code reads.

Issue #147 makes `config_read` and `config_schema` a biconditional: a manifest that
requests the permission without declaring a schema is no longer discovered or
installed. A schema declared without the permission is equally invalid. That rule is
about discovery. It says nothing about whether the schema is any good. A schema open at
a nested level buys the operator nothing while looking compliant. So does one that
declares keys the code never reads.

This script checks the half that carries the safety, from the manifests and the guest
source shipped beside them. Python standard library only, offline, well under a
second. `tomllib` is stdlib from 3.11 (this run was 3.11.5, CI's packager image is
3.12.8), so nothing here needs installing.

What a passing run proves, per plugin:

  * the schema is Draft 2020-12 and closed at every object level, not only the root.
    The walk descends properties, patternProperties, items, prefixItems, $defs and
    every applicator keyword, so a nested object that forgot
    `additionalProperties = false` fails the run
  * every declared property carries a type and a description, so an operator filling
    the value in is never guessing. The tool-argument schema in each `src/lib.rs`
    already describes every argument the model can pass. Config is the surface a
    human types by hand, so it earns the same treatment
  * no declared key can name key material. Nothing outside the declared set is
    accepted at all. The rule is derived in two parts, because a name and a sentence
    carry different signals. A property name is split into words (`nonce_account`
    becomes nonce, account), each word is singularized and matched against the secret
    vocabulary (key, keypair, keystore, secret, seed, mnemonic, private, passphrase,
    password, token, credential, wallet, signer, auth). The glued spellings (`apikey`,
    `privatekey`, `seedphrase`) are matched too, so dropping a separator dodges
    nothing. A description is matched against phrases rather than words,
    because "holds no keys" is a disclaimer and "your wallet private key" is a
    declaration: a sentence that negates the phrase is read as the disclaimer it is.
    The positive half of the rule is the set comparison below. The accepted fields
    are exactly the ones the tool needs. `additionalProperties = false` means an
    operator cannot add a `private_key` field even deliberately
  * the declared keys and the keys the component actually reads are the same set, in
    both directions. An undeclared key that is read is a hole in the schema. A
    declared key nothing reads is a lie in it
  * `config_read` and `config_schema` travel together both ways, per #147. `env_read`
    counts as `config_read`, the serde alias the registry builder accepts
  * the host limits #147 states hold: no `$id`, `$ref` a local pointer only, under
    64 KiB serialized, no deeper than 32 levels
  * no manifest carries the retired `[[plugins.entries]]` block. An instance id, where
    one appears, has the `zpi1_` shape the host derives from package, capability and
    binding rather than a package name

What it does not prove, stated here because a narrow proof is worth more than one that
oversells itself:

  * a schema cannot police values. `rpc_url` is a string and an operator can put
    `?api-key=` in it. The claim is that no field invites key material and that no
    field outside the declared set exists, not that nobody can paste a secret into
    one. The value side is covered where it belongs. `policy.rs` never echoes a config
    value into a model-visible error. `tests/custody.rs` proves a key-shaped config key
    or argument is refused at runtime
  * the read side is a source scan, not a run of the component. It reads the plugin's
    own `src/*.rs` plus the core module its config gate lives in, with `#[cfg(test)]`
    tails cut so a fixture cannot vouch for the surface it was written against. It
    fails closed: a read this scan does not recognise leaves a gate key with nothing
    reading it, which is a failure, not a silent pass
  * `zpi1_` keys are generated by the host at install time, so the prefix and the
    shape are checkable offline and the derivation is not

Usage, from anywhere (paths resolve from this file):

    python3 demo/verify-config-closure.py                        # the three manifests
    python3 demo/verify-config-closure.py path/to/manifest.toml   # explicit paths
"""

from __future__ import annotations

import json
import re
import sys
import tomllib
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
PLUGINS = ("nonce-status", "payment-watch", "spl-transfer-build")

DRAFT_2020_12 = "https://json-schema.org/draft/2020-12/schema"

# `env_read` is the serde alias for `config_read` the registry builder accepts
# (tools/build-registry.py), so the biconditional has to treat the two as one.
CONFIG_PERMISSIONS = ("config_read", "env_read")

# Host limits stated in issue #147.
MAX_SCHEMA_BYTES = 64 * 1024
MAX_SCHEMA_DEPTH = 32

# Short enough to let a terse field pass, long enough to reject a placeholder.
MIN_DESCRIPTION = 10

# The instance key the host derives from package, capability and binding. The
# derivation is host-internal, so the prefix and the shape are what a manifest
# can be held to offline.
INSTANCE_KEY_RE = re.compile(r"^zpi1_[0-9a-z][0-9a-z_-]{3,}$")
INSTANCE_KEY_FIELDS = ("instance_id", "instance_key", "instance", "entry_key", "entry_id")

# A config key is named by its author, so names get the word rule.
SECRET_WORDS = {
    "auth",
    "credential",
    "key",
    "keypair",
    "keystore",
    "mnemonic",
    "passphrase",
    "password",
    "priv",
    "private",
    "secret",
    "seed",
    "sign",
    "signer",
    "signing",
    "token",
    "wallet",
}

# Glued spellings, matched against the name with its separators removed.
GLUED_SECRETS = (
    "apikey",
    "keypair",
    "keystore",
    "mnemonic",
    "passphrase",
    "privatekey",
    "privkey",
    "secretkey",
    "seedphrase",
)

# Prose gets phrases, so a description is free to say what the field is not.
SECRET_PHRASES = (
    "access token",
    "api key",
    "api-key",
    "apikey",
    "auth token",
    "bearer token",
    "credential",
    "id.json",
    "key material",
    "key pair",
    "keypair",
    "mnemonic",
    "passphrase",
    "password",
    "private key",
    "secret key",
    "seed phrase",
    "signing key",
    "wallet key",
)

# Word-bounded, because "no" as a substring lives inside "nonce".
NEGATION_RE = re.compile(
    r"\b(no|not|none|never|cannot|can't|won't|without|refuses?|rejects?|forbids?)\b"
)

# `const KNOWN_KEYS: &[&str] = &[...]`: the fail-closed allowlist each component
# checks every config key against before it reads any of them.
GATE_RE = re.compile(r"const\s+KNOWN_KEYS\s*:\s*&\[&str\]\s*=\s*&\[(?P<body>[^\]]*)\]", re.S)
LITERAL_RE = re.compile(r'"([^"]*)"')
GET_RE = re.compile(r'\.get\(\s*"(?P<key>[^"]+)"\s*\)')
TEST_MOD_RE = re.compile(r"^[ \t]*#\[cfg\(test\)\]", re.M)


def rel(path: Path) -> str:
    """A path a reader can paste, repo-relative whenever it is inside the repo."""
    try:
        return str(path.resolve().relative_to(REPO_ROOT))
    except ValueError:
        return str(path)


def line_of(text: str, index: int) -> int:
    return text.count("\n", 0, index) + 1


def name_words(name: str) -> set[str]:
    """The words in a property name, snake_case and camelCase both, singularized."""
    spaced = re.sub(r"(?<=[a-z0-9])(?=[A-Z])", "_", name)
    words = set()
    for part in re.split(r"[^A-Za-z0-9]+", spaced.lower()):
        if not part:
            continue
        words.add(part)
        if len(part) > 3 and part.endswith("s"):
            words.add(part[:-1])
    return words


def name_is_secretish(name: str) -> list[str]:
    """Secret vocabulary in a property name. No escape clause: names are chosen."""
    hits = set(name_words(name) & SECRET_WORDS)
    glued = "".join(ch for ch in name.lower() if ch.isalnum())
    hits.update(word for word in GLUED_SECRETS if word in glued)
    return sorted(hits)


def description_is_secretish(text: str) -> list[str]:
    """Phrases claiming the value holds key material, disclaimers excluded.

    Sentence by sentence, because a description is allowed to say "holds no keys"
    and that sentence must not be read as an admission.
    """
    hits = set()
    for sentence in re.split(r"[.;\n]", text.lower()):
        if NEGATION_RE.search(sentence):
            continue
        hits.update(phrase for phrase in SECRET_PHRASES if phrase in sentence)
    return sorted(hits)


def subschemas(node: dict):
    """Every child schema of `node`, each with the step that reaches it."""
    for keyword in ("properties", "patternProperties", "$defs", "definitions"):
        for name, child in (node.get(keyword) or {}).items():
            yield f"{keyword}/{name}", child
    for keyword in ("items", "contains", "not", "if", "then", "else", "propertyNames",
                    "additionalProperties", "unevaluatedProperties"):
        child = node.get(keyword)
        if isinstance(child, dict):
            yield keyword, child
    for keyword in ("allOf", "anyOf", "oneOf", "prefixItems"):
        for index, child in enumerate(node.get(keyword) or []):
            yield f"{keyword}/{index}", child


def is_object_level(node: dict) -> bool:
    """Anything that can carry properties, declared or not, has to be closed."""
    return node.get("type") == "object" or bool(
        {"properties", "patternProperties", "required", "propertyNames"} & set(node)
    )


def check_property(pointer: str, name: str, prop, problems: list[str]) -> None:
    """One field an operator has to fill in: typed, described, never key-shaped."""
    if not isinstance(prop, dict):
        problems.append(f"{pointer} is {prop!r}, not a schema, so it declares no type")
        return
    if not prop.get("type") or not isinstance(prop.get("type"), (str, list)):
        problems.append(
            f"{pointer} declares no type, so the host cannot validate it and the "
            "operator is guessing what to put there"
        )
    description = prop.get("description")
    if not isinstance(description, str) or len(description.strip()) < MIN_DESCRIPTION:
        problems.append(
            f"{pointer} has no usable description (at least {MIN_DESCRIPTION} "
            "characters saying what the operator should set)"
        )
        description = ""
    name_hits = name_is_secretish(name)
    if name_hits:
        problems.append(
            f"{pointer} is named for key material ({', '.join(name_hits)}): this "
            "package accepts no key, so no config field may invite one"
        )
    prose_hits = description_is_secretish(description)
    if prose_hits:
        problems.append(
            f"{pointer} describes key material ({', '.join(prose_hits)}): a config "
            "field holding one cannot exist in a package with no way to use it"
        )


def walk_schema(node, pointer: str, depth: int, stats: dict, problems: list[str]) -> None:
    """Check one schema level, then every level under it."""
    if not isinstance(node, dict):
        problems.append(f"{pointer or '/'} is {type(node).__name__}, not a schema")
        return
    stats["depth"] = max(stats["depth"], depth)
    if "$id" in node:
        problems.append(f"{pointer or '/'} declares $id, which #147's host rejects")
    ref = node.get("$ref")
    if isinstance(ref, str) and not ref.startswith("#"):
        problems.append(f"{pointer or '/'} has a non-local $ref ({ref}); #147 allows a local pointer only")
    if is_object_level(node):
        stats["objects"] += 1
        if node.get("additionalProperties") is not False:
            found = (
                "absent"
                if "additionalProperties" not in node
                else json.dumps(node["additionalProperties"])
            )
            problems.append(
                f"{pointer or '/'} is an object level with additionalProperties "
                f"{found}, so it accepts keys nobody declared"
            )
        properties = node.get("properties") or {}
        for name, prop in properties.items():
            stats["properties"] += 1
            check_property(f"{pointer}/properties/{name}", name, prop, problems)
        for name in node.get("required") or []:
            if name not in properties:
                problems.append(f"{pointer or '/'} requires {name}, which it never declares")
    for step, child in subschemas(node):
        walk_schema(child, f"{pointer}/{step}", depth + 1, stats, problems)


def host_source(path: Path) -> str:
    """A source file with its `#[cfg(test)]` tail cut off.

    Line numbers above the cut are untouched. A test fixture can no longer vouch
    for the config surface it was written against.
    """
    text = path.read_text(encoding="utf-8")
    match = TEST_MOD_RE.search(text)
    return text[: match.start()] if match else text


def config_reads(text: str) -> dict[str, int]:
    """Config keys this file reads, each keyed to the line that reads it.

    A `.get("x")` counts only when the receiver in the same statement mentions the
    config map, which is what separates `args.config.get("rpc_url")` and
    `v.get("__config")?.get("rpc_url")?` from every other map lookup in the file.
    """
    found: dict[str, int] = {}
    for match in GET_RE.finditer(text):
        key = match.group("key")
        if key == "__config":
            continue
        statement = text[max(0, match.start() - 400) : match.start()]
        statement = statement[statement.rfind(";") + 1 :]
        if "config" not in statement:
            continue
        found.setdefault(key, line_of(text, match.start()))
    return found


def follow_delegated_gate(
    plugin_dir: Path, delegates: list[Path], reads: dict[str, list[str]], problems: list[str]
) -> tuple[list[str], str]:
    """The gate for a guest that hands config parsing to the vendored core."""
    if not delegates:
        problems.append(
            "no KNOWN_KEYS gate and no parse_policy call, so nothing in this package "
            "bounds the config keys it will accept"
        )
        return [], ""
    core = plugin_dir / "solana-core" / "src" / "policy.rs"
    if not core.is_file():
        problems.append(f"config parsing is delegated to parse_policy but {rel(core)} is missing")
        return [], ""
    text = host_source(core)
    match = GATE_RE.search(text)
    if not match:
        problems.append(f"{rel(core)} declares no KNOWN_KEYS, so parse_policy bounds nothing")
        return [], ""
    for key, line in config_reads(text).items():
        reads.setdefault(key, []).append(f"{rel(core)}:{line}")
    gate = LITERAL_RE.findall(match.group("body"))
    return gate, f"{rel(core)}:{line_of(text, match.start())}"


def config_surface(
    plugin_dir: Path, problems: list[str]
) -> tuple[set[str], dict[str, list[str]], list[str]]:
    """The config keys this component reads, with the evidence for each one.

    The gate is the definitive set. Every component checks each incoming key
    against its own `KNOWN_KEYS` and refuses anything else, so a key outside the
    gate cannot be read even if a line asks for it. `spl-transfer-build` has no gate
    of its own because it delegates to `parse_policy`, so the gate is followed into
    the core module the guest imports.
    """
    reads: dict[str, list[str]] = {}
    notes: list[str] = []
    sources = sorted((plugin_dir / "src").glob("*.rs"))
    if not sources:
        problems.append(f"no guest source under {rel(plugin_dir / 'src')}, so the read side is unknown")
        return set(), reads, notes
    gate: list[str] = []
    gate_at = ""
    delegates: list[Path] = []
    for path in sources:
        text = host_source(path)
        for key, line in config_reads(text).items():
            reads.setdefault(key, []).append(f"{rel(path)}:{line}")
        match = GATE_RE.search(text)
        if match:
            if gate:
                problems.append(
                    f"two KNOWN_KEYS gates ({gate_at} and {rel(path)}), so the "
                    "accepted set is ambiguous"
                )
            gate = LITERAL_RE.findall(match.group("body"))
            gate_at = f"{rel(path)}:{line_of(text, match.start())}"
        if "parse_policy" in text:
            delegates.append(path)
    if gate and delegates:
        problems.append(
            f"{rel(delegates[0])} calls parse_policy while {gate_at} declares a gate "
            "of its own, so two allowlists decide what config this guest accepts"
        )
    if gate:
        notes.append(
            f"gate {gate_at}. No file here calls parse_policy, so the wider policy "
            "gate in the vendored core is unreachable from this component"
        )
    else:
        gate, gate_at = follow_delegated_gate(plugin_dir, delegates, reads, problems)
        if gate:
            notes.append(f"gate {gate_at}, delegated by {rel(delegates[0])} through parse_policy")
    for key in sorted(set(gate) - set(reads)):
        problems.append(f"the gate at {gate_at} accepts {key} but no read of it was found")
    for key in sorted(set(reads) - set(gate)):
        problems.append(
            f"{reads[key][0]} reads {key}, which the gate at {gate_at} refuses, so that "
            "read can never run"
        )
    if gate:
        notes.append("accepted config fields, nothing else reachable: " + ", ".join(sorted(gate)))
    return set(gate) | set(reads), reads, notes


def check(manifest_path: Path) -> bool:
    """One manifest against one component. Prints its own block, returns the verdict."""
    problems: list[str] = []
    try:
        manifest = tomllib.loads(manifest_path.read_text(encoding="utf-8"))
    except (OSError, tomllib.TOMLDecodeError) as err:
        print(f"\n{rel(manifest_path)}\n  FAIL cannot be read as TOML: {err}")
        return False

    name = manifest.get("name", "(unnamed)")
    permissions = [str(p).lower() for p in manifest.get("permissions") or []]
    grants_config = any(p in CONFIG_PERMISSIONS for p in permissions)
    schema = manifest.get("config_schema")
    stats = {"objects": 0, "properties": 0, "depth": 0}
    size = 0

    if schema is None:
        if grants_config:
            problems.append("requests config_read with no config_schema, which #147 makes undiscoverable")
        else:
            problems.append("declares neither config_read nor config_schema, so there is no config surface here")
    elif not isinstance(schema, dict):
        problems.append(f"config_schema is a {type(schema).__name__}, not a table")
    else:
        if not grants_config:
            problems.append(
                "declares config_schema without requesting config_read, which #147 "
                "makes equally invalid"
            )
        if schema.get("$schema") != DRAFT_2020_12:
            problems.append(f"root $schema is {schema.get('$schema')!r}, not Draft 2020-12 ({DRAFT_2020_12})")
        if schema.get("type") != "object":
            problems.append(f"root type is {schema.get('type')!r}, not object")
        if not (schema.get("properties") or {}):
            problems.append("declares no properties, so the config_read grant is not enumerable")
        size = len(json.dumps(schema, separators=(",", ":")).encode())
        if size > MAX_SCHEMA_BYTES:
            problems.append(f"serializes to {size} bytes, over #147's {MAX_SCHEMA_BYTES} byte host limit")
        walk_schema(schema, "", 1, stats, problems)
        if stats["depth"] > MAX_SCHEMA_DEPTH:
            problems.append(f"nests {stats['depth']} levels, over #147's {MAX_SCHEMA_DEPTH} level host limit")

    plugins_table = manifest.get("plugins")
    if isinstance(plugins_table, dict) and "entries" in plugins_table:
        problems.append(
            "carries a [[plugins.entries]] block, the retired keyed-by-name form. "
            "Instance config is keyed on the zpi1_ instance id now"
        )
    for field in INSTANCE_KEY_FIELDS:
        if field not in manifest:
            continue
        value = manifest[field]
        if not isinstance(value, str) or not INSTANCE_KEY_RE.match(value):
            problems.append(
                f"{field} = {value!r} is not a zpi1_ instance id. The host derives that "
                "key from package, capability and binding. `zeroclaw plugin info "
                "<package>` prints it"
            )
        elif value == f"zpi1_{name}":
            problems.append(f"{field} = {value!r} is the package name behind the prefix, not a derived key")

    declared = (schema.get("properties") or {}) if isinstance(schema, dict) else {}
    read_keys, reads, notes = config_surface(manifest_path.parent, problems)
    for key in sorted(set(declared) - read_keys):
        problems.append(
            f"config_schema declares {key}, which nothing reads: the schema is "
            "describing a key that does nothing"
        )
    for key in sorted(read_keys - set(declared)):
        problems.append(
            f"{reads.get(key, ['the gate'])[0]} reads {key}, which config_schema never "
            "declares: a closed schema means the host drops it before the guest runs"
        )

    print(f"\n{name}  {rel(manifest_path)}")
    print(f"  permissions: {', '.join(permissions) or 'none'}")
    if isinstance(schema, dict):
        levels = "level" if stats["objects"] == 1 else "levels"
        fields = "property" if stats["properties"] == 1 else "properties"
        print(
            f"  schema: Draft 2020-12, {size} bytes, {stats['depth']} deep, "
            f"{stats['objects']} object {levels} closed, {stats['properties']} {fields}"
        )
    for note in notes:
        print(f"  {note}")
    print(f"  declared: {', '.join(sorted(declared)) or 'nothing'}")
    for key in sorted(reads):
        print(f"  reads {key} at {', '.join(reads[key])}")
    for problem in problems:
        print(f"  FAIL {problem}")
    if not problems:
        print(
            "  PASS closed at every object level, every field typed and described, "
            "declared set equal to the read set, no field able to name key material"
        )
    return not problems


def main(argv: list[str]) -> int:
    if argv:
        paths = [Path(a) for a in argv]
    else:
        paths = [REPO_ROOT / "plugins" / plugin / "manifest.toml" for plugin in PLUGINS]
    missing = [p for p in paths if not p.is_file()]
    if missing:
        print("manifest not found: " + ", ".join(str(p) for p in missing))
        return 2
    results = [check(path) for path in paths]
    passed = sum(results)
    total = len(results)
    counted = "manifest" if total == 1 else "manifests"
    if passed == total:
        print(
            f"\nPASS {passed} of {total} {counted}. Every config field is declared, "
            "typed and described, the schema is closed at every object level, the declared "
            "set is exactly the set the components read and no field can name key material."
        )
        return 0
    failed = [rel(p) for p, ok in zip(paths, results) if not ok]
    print(f"\nFAIL {len(failed)} of {total} {counted}: {', '.join(failed)}")
    return 1


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
